/*
 * Author: Miguel A. Lopez
 * Company: RankUp Games LLC
 * Project: WispKey
 * Description: .env file importer -- parses env files, auto-detects credential types
 *              via regex heuristics, encrypts and stores them, outputs a .env.wispkey
 *              file with phantom tokens.
 * Created: 2026-04-07
 * Last Modified: 2026-04-08
 */

use std::fs;
use std::path::Path;
use std::sync::OnceLock;

use regex::Regex;

use crate::audit;
use crate::core::{CredentialType, Vault, VaultError};

pub struct ImportResults {
    pub imported: usize,
    pub skipped: usize,
    pub errors: usize,
    pub output_path: String,
}

struct EnvEntry {
    key: String,
    value: String,
}

pub fn import_env_file(
    vault: &Vault,
    path: &str,
    prefix: Option<&str>,
    partition: Option<&str>,
) -> crate::core::Result<ImportResults> {
    let content = fs::read_to_string(path).map_err(VaultError::Io)?;
    let entries = parse_env(&content);

    if entries.is_empty() {
        return Ok(ImportResults {
            imported: 0,
            skipped: 0,
            errors: 0,
            output_path: String::new(),
        });
    }

    let mut imported = 0;
    let mut skipped = 0;
    let mut errors = 0;
    let mut output_lines: Vec<String> = Vec::new();

    let prefix_str = prefix.unwrap_or("");

    for entry in &entries {
        let base_name = env_key_to_credential_name(&entry.key);
        let cred_name = if prefix_str.is_empty() {
            base_name
        } else {
            format!("{}-{}", prefix_str, base_name)
        };
        let detected_type = detect_credential_type(&entry.value);

        match vault.add_credential(
            &cred_name,
            detected_type,
            &entry.value,
            None,
            Some("imported"),
            partition,
        ) {
            Ok(cred) => {
                audit::log_event(
                    vault.db(),
                    "CredentialAdded",
                    Some(&cred_name),
                    Some(&cred.wisp_token),
                    None,
                    None,
                    None,
                    None,
                    false,
                    None,
                    None,
                );
                output_lines.push(format!("{}={}", entry.key, cred.wisp_token));
                println!(
                    "  + {} -> {} ({})",
                    entry.key,
                    cred.wisp_token,
                    cred.credential_type.display_name()
                );
                imported += 1;
            }
            Err(VaultError::DuplicateCredential(_)) => {
                println!("  ~ {} skipped (already exists)", entry.key);
                skipped += 1;
            }
            Err(e) => {
                eprintln!("  ! {} error: {}", entry.key, e);
                errors += 1;
            }
        }
    }

    let mut output_path = String::new();
    if !output_lines.is_empty() {
        let env_path = Path::new(path);
        let out_name = format!(
            "{}.wispkey",
            env_path.file_name().unwrap_or_default().to_string_lossy()
        );
        let out_path = env_path.parent().unwrap_or(Path::new(".")).join(out_name);
        let header = "# Generated by WispKey -- use these wisp tokens instead of real credentials\n# Set HTTP_PROXY=http://localhost:7700 in your agent environment\n\n";
        fs::write(
            &out_path,
            format!("{}{}\n", header, output_lines.join("\n")),
        )?;
        output_path = out_path.to_string_lossy().to_string();
    }

    Ok(ImportResults {
        imported,
        skipped,
        errors,
        output_path,
    })
}

fn parse_env(content: &str) -> Vec<EnvEntry> {
    let mut entries = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let line_content = trimmed.strip_prefix("export ").unwrap_or(trimmed);

        if let Some(eq_pos) = line_content.find('=') {
            let key = line_content[..eq_pos].trim().to_string();
            let mut value = line_content[eq_pos + 1..].trim().to_string();

            if (value.starts_with('"') && value.ends_with('"'))
                || (value.starts_with('\'') && value.ends_with('\''))
            {
                value = value[1..value.len() - 1].to_string();
            }

            if !key.is_empty() && !value.is_empty() {
                entries.push(EnvEntry { key, value });
            }
        }
    }

    entries
}

struct CredentialPatterns {
    openai: Regex,
    github_pat: Regex,
    github_app: Regex,
    slack_bot: Regex,
    slack_user: Regex,
    aws_access: Regex,
    basic_auth: Regex,
    bearer: Regex,
}

static CREDENTIAL_PATTERNS: OnceLock<CredentialPatterns> = OnceLock::new();

fn get_patterns() -> &'static CredentialPatterns {
    CREDENTIAL_PATTERNS.get_or_init(|| CredentialPatterns {
        openai: Regex::new(r"^sk-[a-zA-Z0-9]{20,}$").unwrap(),
        github_pat: Regex::new(r"^ghp_[a-zA-Z0-9]{36}$").unwrap(),
        github_app: Regex::new(r"^ghs_[a-zA-Z0-9]{36}$").unwrap(),
        slack_bot: Regex::new(r"^xoxb-[0-9]+-[a-zA-Z0-9]+$").unwrap(),
        slack_user: Regex::new(r"^xoxp-[0-9]+-[a-zA-Z0-9]+$").unwrap(),
        aws_access: Regex::new(r"^AKIA[A-Z0-9]{16}$").unwrap(),
        basic_auth: Regex::new(r"^Basic [A-Za-z0-9+/=]+$").unwrap(),
        bearer: Regex::new(r"^Bearer [a-zA-Z0-9._\-]+$").unwrap(),
    })
}

fn env_key_to_credential_name(key: &str) -> String {
    let mut result = String::with_capacity(key.len() + 8);
    let chars: Vec<char> = key.chars().collect();

    for (index, &character) in chars.iter().enumerate() {
        if character == '_' {
            if !result.is_empty() && !result.ends_with('-') {
                result.push('-');
            }
            continue;
        }

        if character.is_uppercase() && index > 0 {
            let previous = chars[index - 1];
            if previous.is_lowercase() || previous.is_ascii_digit() {
                if !result.ends_with('-') {
                    result.push('-');
                }
            } else if previous.is_uppercase()
                && let Some(&next) = chars.get(index + 1)
                && next.is_lowercase()
                && !result.ends_with('-')
            {
                result.push('-');
            }
        }

        result.push(character.to_ascii_lowercase());
    }

    result.trim_matches('-').to_string()
}

fn detect_credential_type(value: &str) -> CredentialType {
    let patterns = get_patterns();

    if patterns.openai.is_match(value)
        || patterns.github_pat.is_match(value)
        || patterns.github_app.is_match(value)
        || patterns.slack_bot.is_match(value)
        || patterns.slack_user.is_match(value)
        || patterns.bearer.is_match(value)
    {
        return CredentialType::BearerToken;
    }

    if patterns.aws_access.is_match(value) {
        return CredentialType::ApiKey;
    }

    if patterns.basic_auth.is_match(value) {
        return CredentialType::BasicAuth;
    }

    CredentialType::BearerToken
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn naming_screaming_snake() {
        assert_eq!(env_key_to_credential_name("DB_PASSWORD"), "db-password");
        assert_eq!(
            env_key_to_credential_name("AUTH_SERVICE_BASE"),
            "auth-service-base"
        );
        assert_eq!(
            env_key_to_credential_name("REDIS_SSL_HOST"),
            "redis-ssl-host"
        );
    }

    #[test]
    fn naming_camel_case() {
        assert_eq!(env_key_to_credential_name("simpleKey"), "simple-key");
        assert_eq!(
            env_key_to_credential_name("MareSynchronosJwt"),
            "mare-synchronos-jwt"
        );
    }

    #[test]
    fn naming_camel_case_with_acronym() {
        assert_eq!(
            env_key_to_credential_name("MareSynchronosDiscordOAuthClientSecret"),
            "mare-synchronos-discord-o-auth-client-secret"
        );
        assert_eq!(env_key_to_credential_name("HTTPSProxy"), "https-proxy");
    }

    #[test]
    fn naming_single_word() {
        assert_eq!(env_key_to_credential_name("PORT"), "port");
        assert_eq!(env_key_to_credential_name("port"), "port");
    }

    #[test]
    fn naming_mixed_underscores_and_camel() {
        assert_eq!(
            env_key_to_credential_name("MareSynchronos_VanityRoles"),
            "mare-synchronos-vanity-roles"
        );
    }

    #[test]
    fn naming_no_leading_trailing_hyphens() {
        assert_eq!(env_key_to_credential_name("_PRIVATE_KEY_"), "private-key");
    }

    #[test]
    fn detect_openai_key() {
        assert_eq!(
            detect_credential_type("sk-abcdefghijklmnopqrstuvwxyz1234567890abcd").display_name(),
            "bearer_token"
        );
    }

    #[test]
    fn detect_github_pat() {
        assert_eq!(
            detect_credential_type("ghp_abcdefghijklmnopqrstuvwxyz1234567890").display_name(),
            "bearer_token"
        );
    }

    #[test]
    fn detect_basic_auth() {
        assert_eq!(
            detect_credential_type("Basic dXNlcjpwYXNz").display_name(),
            "basic_auth"
        );
    }

    #[test]
    fn detect_aws_access_key() {
        assert_eq!(
            detect_credential_type("AKIAIOSFODNN7EXAMPLE").display_name(),
            "api_key"
        );
    }

    #[test]
    fn detect_generic_falls_back_to_bearer() {
        assert_eq!(
            detect_credential_type("some-random-value-123").display_name(),
            "bearer_token"
        );
    }

    #[test]
    fn parse_env_basic() {
        let content = "KEY1=value1\nKEY2=value2\n# comment\n\nKEY3=\"quoted\"";
        let entries = parse_env(content);
        assert_eq!(entries.len(), 3);
        assert_eq!(entries[0].key, "KEY1");
        assert_eq!(entries[0].value, "value1");
        assert_eq!(entries[2].value, "quoted");
    }

    #[test]
    fn parse_env_export_prefix() {
        let content = "export MY_KEY=my_value";
        let entries = parse_env(content);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].key, "MY_KEY");
        assert_eq!(entries[0].value, "my_value");
    }

    #[test]
    fn parse_env_skips_empty_values() {
        let content = "EMPTY=\nVALID=yes";
        let entries = parse_env(content);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].key, "VALID");
    }
}
